services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3107:3107"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
